/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        'surface-variant': '#33343b',
        'primary': '#4be277',
        'on-surface': '#e2e2eb',
        'text-secondary': '#9CA3AF',
        'secondary-container': '#0566d9',
        'border-subtle': '#2A2E3A',
        'on-primary-container': '#004b1e',
        'surface-container-low': '#191b22',
        'surface-container-lowest': '#0c0e14',
        'on-primary-fixed': '#002109',
        'primary-container': '#22c55e',
        'accent-red': '#EF4444',
        'surface-bright': '#373940',
        'surface-tint': '#4ae176',
        'surface-container-high': '#282a30',
        'on-secondary-fixed-variant': '#004395',
        'on-surface-variant': '#bccbb9',
        'tertiary-container': '#ff8b7c',
        'on-secondary-container': '#e6ecff',
        'background': '#111319',
        'surface-dim': '#111319',
        'print-white': '#FFFFFF',
        'inverse-surface': '#e2e2eb',
        'accent-amber': '#F59E0B',
        'nav-top': '#141720',
        'inverse-on-surface': '#2e3037',
        'surface-container-highest': '#33343b',
        'surface-container': '#1e1f26',
        'on-primary': '#003915',
        'surface-hover': '#242836',
        'outline': '#869585',
        'primary-fixed-dim': '#4ae176',
        'on-background': '#e2e2eb',
        'tertiary': '#ffb5ab',
        'on-secondary': '#002e6a',
        'secondary': '#adc6ff',
        'accent-teal': '#14B8A6',
        'surface': '#1A1D27',
        'text-primary': '#F1F3F5',
        'error-container': '#93000a',
        'primary-fixed': '#6bff8f',
        'outline-variant': '#3d4a3d',
        'inverse-primary': '#006e2f',
        'on-primary-fixed-variant': '#005321',
      },
      borderRadius: {
        DEFAULT: '0.5rem',
        sm: '0.25rem',
        lg: '0.75rem',
        xl: '1rem',
        full: '9999px',
      },
      spacing: {
        base: '8px',
        'input-height': '40px',
        'sidebar-collapsed': '64px',
        'container-padding': '32px',
        'sidebar-width': '240px',
        'table-row-height': '48px',
        'top-nav-height': '56px',
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
      },
      fontSize: {
        'body-sm': ['13px', { lineHeight: '18px', fontWeight: '400' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-caps': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
        'headline-lg': ['28px', { lineHeight: '36px', fontWeight: '700' }],
        'headline-md': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'headline-sm': ['16px', { lineHeight: '24px', fontWeight: '600' }],
        'data-mono': ['13px', { lineHeight: '20px', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
};
